# -*- coding: utf-8 -*-
"""sistema_especialista_R.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-7oHmmixV_nDAONArN4iLNqknk9Flih
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# install.packages('/content/expert_1_0-0.tar.gz', repos = NULL, type="source")
# 
# library(expert)
# 
# x <- list(EXP1 <- list(INT <- c(150000, 180000, 190000)),
#           EXP2 <- list(INT <- c(110000, 120000, 130000)),
#           EXP3 <- list(INT <- c(200000, 300000, 400000)))
# 
# prob <- c(0.1, 0.5, 0.9)
# 
# inf <- expert(x, "weights", prob, w=c(.6,.3,.1))
# 
# hist(inf,col = "blue")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# print(summary(inf))
# 
# print(quantile(inf))
# 
# cat("\n")
# cat("Valor médio", mean(inf))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# par(bg = "white")
# split.screen(c(2,2))
# 
# screen(1)
# hist(inf,col="gray",main="Distribuição agregada")
# 
# screen(2)
# s = density(c(150000, 180000, 190000))
# plot(s,main="Especialista 1")
# polygon(s,col="blue")
# 
# screen(3)
# s = density(c(110000, 120000, 130000))
# plot(s,main="Especialista 2")
# polygon(s,col="blue")
# 
# screen(4)
# s = density(c(200000, 300000, 400000))
# plot(s,main="Especialista 3")
# polygon(s,col="blue")
# 
# close.screen(all = TRUE)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# x <- list(EXP1 <- list(SEM1 <- c(1100, 1150, 1200),
#                        SEM2 <- c(12, 15, 16),
#                        INT  <- c(150000, 180000, 190000)),
#           EXP2 <- list(SEM1 <- c(1200, 1300, 1400),
#                        SEM2 <- c(15, 16, 18),
#                        INT  <- c(110000, 120000, 130000)),
#           EXP3 <- list(SEM1 <- c(1700, 1900, 2100),
#                        SEM2 <- c(18, 19, 20),
#                        INT  <- c(200000, 300000, 400000)))
# 
# prob <- c(0.1, 0.5, 0.9)
# 
# semverd <- c(1200, 16)
# 
# inf <- expert(x, "cooke", prob, semverd)
# 
# hist(inf,col = "blue")
# 
# print(summary(inf))
# 
# print(quantile(inf))
# 
# cat("\n")
# cat("Valor médio", mean(inf))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# par(bg = "white")
# split.screen(c(2,2))
# 
# screen(1)
# hist(inf,col="gray",main="Distribuição agregada")
# 
# screen(2)
# s = density(c(150000, 180000, 190000))
# plot(s,main="Especialista 1")
# polygon(s,col="blue")
# 
# screen(3)
# s = density(c(110000, 120000, 130000))
# plot(s,main="Especialista 2")
# polygon(s,col="blue")
# 
# screen(4)
# s = density(c(200000, 300000, 400000))
# plot(s,main="Especialista 3")
# polygon(s,col="blue")
# 
# close.screen(all = TRUE)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # EXERCICIO SOBRE SISTEMA ESPECIALISTA
# # INT  = CUSTO DA IMPLANTAÇÃO DE AR CONDICIONADOS
# # SEM1 = CUSTO COM A ENERGIA PARA A MARCA SUGERIDA
# # SEM2 = QUANTIDADE DE AR CONDICIONADOS SUGERIDOS
# # SEM3 = CUSTO UNIDADE DO AR CONDICIONADO
# # SEM4 = DIAS PARA IMPLANTAÇÃO
# 
# x <- list(EXP1 <- list(SEM1 <- c(500, 600, 800),
#                        SEM2 <- c(11, 12, 15),
#                        SEM3 <- c(1500, 1600, 2000),
#                        SEM4 <- c(10, 15, 16),
#                        INT  <- c(40000, 50000, 60000)),
#           EXP2 <- list(SEM1 <- c(800, 900, 1000),
#                        SEM2 <- c(15, 19, 20),
#                        SEM3 <- c(1900, 2100, 2600),
#                        SEM4 <- c(15, 17, 19),
#                        INT  <- c(60000, 70000, 75000)),
#           EXP3 <- list(SEM1 <- c(500, 600, 700),
#                        SEM2 <- c(10, 11, 13),
#                        SEM3 <- c(1000, 1200, 1400),
#                        SEM4 <- c(10, 11, 12),
#                        INT  <- c(30000, 40000, 45000)),
#           EXP4 <- list(SEM1 <- c(1000, 1500, 1700),
#                        SEM2 <- c(13, 16, 18),
#                        SEM3 <- c(1400, 2100, 3000),
#                        SEM4 <- c(10, 11, 12),
#                        INT  <- c(30000, 50000, 65000)))
# 
# prob <- c(0.1, 0.5, 0.9)
# 
# semverd <- c(600, 15, 2100, 18)
# 
# inf <- expert(x, "cooke", prob, semverd)
# 
# hist(inf,col = "blue")
# 
# print(summary(inf))
# 
# print(quantile(inf))
# 
# cat("\n")
# cat("Valor médio", mean(inf))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# par(bg = "white")
# split.screen(c(2,2))
# 
# screen(1)
# s = density(c(40000, 50000, 60000))
# plot(s,main="Especialista 1")
# polygon(s,col="blue")
# 
# screen(2)
# s = density(c(60000, 70000, 75000))
# plot(s,main="Especialista 2")
# polygon(s,col="blue")
# 
# screen(3)
# s = density(c(30000, 40000, 45000))
# plot(s,main="Especialista 3")
# polygon(s,col="blue")
# 
# screen(4)
# s = density(c(30000, 50000, 65000))
# plot(s,main="Especialista 4")
# polygon(s,col="blue")
# 
# close.screen(all = TRUE)